#!/bin/bash
#
# chkconfig: 35 90 12
# description: MAT server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service MAT
start() {
	nohup my_command > /var/logs/inputprocess.log 2>&1&
	echo $! > /var/logs/save_pid.txt
}
# Restart the service MAT
stop() {
        kill -9 `cat /var/logs/save_pid.txt`
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status MAT
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
